// app/terms/page.tsx
export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-slate-50 py-12 px-6">
      <div className="max-w-3xl mx-auto bg-white rounded-2xl shadow-sm border border-slate-200 p-8 md:p-12">
        <h1 className="text-3xl font-bold text-slate-900 mb-2">Terms of Service</h1>
        <p className="text-slate-500 mb-8">Last updated: January 12, 2026</p>
        
        <div className="prose prose-slate max-w-none">
          <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-4">1. Acceptance of Terms</h2>
          <p className="text-slate-600 mb-4">
            By accessing or using QuizForge ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.
          </p>
          
          <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-4">2. Description of Service</h2>
          <p className="text-slate-600 mb-4">
            QuizForge is an AI-powered educational platform that enables users to create quizzes and exams from uploaded course materials. The Service includes features for teachers (classroom management, assignments, grading) and students (practice quizzes, progress tracking).
          </p>
          
          <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-4">3. User Accounts</h2>
          <ul className="list-disc pl-6 text-slate-600 mb-4 space-y-2">
            <li>You must provide accurate and complete information when creating an account</li>
            <li>You are responsible for maintaining the security of your account credentials</li>
            <li>You must notify us immediately of any unauthorized use of your account</li>
            <li>You may not share your account or use another user's account</li>
            <li>You must be at least 13 years old to create an account (or have parental consent)</li>
          </ul>
          
          <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-4">4. User Content</h2>
          <h3 className="text-lg font-medium text-slate-800 mt-6 mb-3">4.1 Your Rights</h3>
          <p className="text-slate-600 mb-4">
            You retain ownership of all content you upload to the Service, including documents, course materials, and any quizzes you create.
          </p>
          
          <h3 className="text-lg font-medium text-slate-800 mt-6 mb-3">4.2 License to Us</h3>
          <p className="text-slate-600 mb-4">
            By uploading content, you grant us a limited license to process, store, and display your content solely to provide the Service. This includes sending content to AI services for quiz generation.
          </p>
          
          <h3 className="text-lg font-medium text-slate-800 mt-6 mb-3">4.3 Content Restrictions</h3>
          <p className="text-slate-600 mb-4">You agree not to upload content that:</p>
          <ul className="list-disc pl-6 text-slate-600 mb-4 space-y-2">
            <li>Infringes on intellectual property rights of others</li>
            <li>Contains malware, viruses, or harmful code</li>
            <li>Is illegal, defamatory, or violates any laws</li>
            <li>Contains private information of others without consent</li>
          </ul>
          
          <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-4">5. Acceptable Use</h2>
          <p className="text-slate-600 mb-4">You agree not to:</p>
          <ul className="list-disc pl-6 text-slate-600 mb-4 space-y-2">
            <li>Use the Service for any illegal purpose</li>
            <li>Attempt to gain unauthorized access to the Service or other accounts</li>
            <li>Interfere with or disrupt the Service</li>
            <li>Use automated tools to access the Service (scraping, bots)</li>
            <li>Resell or redistribute the Service without permission</li>
            <li>Use the Service to generate harmful, misleading, or inappropriate content</li>
          </ul>
          
          <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-4">6. AI-Generated Content</h2>
          <p className="text-slate-600 mb-4">
            Quiz questions and content generated by our AI are provided "as is." While we strive for accuracy, AI-generated content may contain errors. You are responsible for reviewing and verifying any quizzes before using them for grading or assessment purposes.
          </p>
          
          <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-4">7. Classroom Features</h2>
          <p className="text-slate-600 mb-4">
            Teachers using classroom features are responsible for:
          </p>
          <ul className="list-disc pl-6 text-slate-600 mb-4 space-y-2">
            <li>Obtaining necessary consents for student data</li>
            <li>Complying with educational privacy laws (e.g., FERPA, COPPA)</li>
            <li>Appropriate use of grading and assessment features</li>
          </ul>
          
          <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-4">8. Intellectual Property</h2>
          <p className="text-slate-600 mb-4">
            The Service, including its design, features, and code, is owned by QuizForge and protected by intellectual property laws. You may not copy, modify, or create derivative works based on the Service.
          </p>
          
          <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-4">9. Payment Terms</h2>
          <p className="text-slate-600 mb-4">
            If you purchase a paid subscription:
          </p>
          <ul className="list-disc pl-6 text-slate-600 mb-4 space-y-2">
            <li>Payments are processed securely through our payment provider</li>
            <li>Subscriptions renew automatically unless cancelled</li>
            <li>You may cancel at any time; access continues until the end of your billing period</li>
            <li>Refunds are provided at our discretion and in accordance with applicable law</li>
          </ul>
          
          <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-4">10. Termination</h2>
          <p className="text-slate-600 mb-4">
            We may suspend or terminate your account if you violate these Terms. You may delete your account at any time. Upon termination, your right to use the Service ceases, and your data may be deleted in accordance with our Privacy Policy.
          </p>
          
          <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-4">11. Disclaimers</h2>
          <p className="text-slate-600 mb-4">
            THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND. WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
          </p>
          
          <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-4">12. Limitation of Liability</h2>
          <p className="text-slate-600 mb-4">
            TO THE MAXIMUM EXTENT PERMITTED BY LAW, QUIZFORGE SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF DATA, USE, OR PROFITS.
          </p>
          
          <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-4">13. Indemnification</h2>
          <p className="text-slate-600 mb-4">
            You agree to indemnify and hold harmless QuizForge from any claims arising from your use of the Service, your content, or your violation of these Terms.
          </p>
          
          <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-4">14. Changes to Terms</h2>
          <p className="text-slate-600 mb-4">
            We may modify these Terms at any time. Continued use of the Service after changes constitutes acceptance of the new Terms. Material changes will be notified via email or prominent notice on the Service.
          </p>
          
          <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-4">15. Governing Law</h2>
          <p className="text-slate-600 mb-4">
            These Terms are governed by the laws of Norway. Any disputes shall be resolved in the courts of Norway.
          </p>
          
          <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-4">16. Contact</h2>
          <p className="text-slate-600 mb-4">
            For questions about these Terms, contact us at:<br />
            <strong>Email:</strong> legal@quizforge.app
          </p>
        </div>
        
        <div className="mt-12 pt-8 border-t border-slate-200">
          <a href="/" className="text-indigo-600 hover:text-indigo-500 font-medium">← Back to QuizForge</a>
        </div>
      </div>
    </div>
  );
}
